---
# ====================================================
# ▶️ Запуск Nginx после установки
# ====================================================
- name: Start service
  service:
    name: nginx
    state: started
    enabled: true

# ====================================================
# 🔄 Перезагрузка nginx для применения новой конфигурации
# ====================================================
- name: Reload nginx
  systemd:
    name: nginx
    state: reloaded