---
- name: Check if all servers are unreachable
  hosts: new_servers
  ignore_unreachable: yes
  tasks:
    - name: Initialize unreachable_hosts list
      set_fact:
        unreachable_hosts: []

    - name: Check if host is unreachable
      set_fact:
        unreachable_hosts: "{{ unreachable_hosts | default([]) + [inventory_hostname] }}"
      when: ansible_facts | length == 0
      loop: "{{ groups['new_servers'] }}"

- name: Configure new servers
  hosts: reachable_new_servers #new_servers
  ignore_unreachable: yes
  gather_facts: yes
  become: yes
  roles:
    - role: initial_setup
      #when: not unreachable_hosts | length == ansible_play_hosts | length

- name: Wait for SSH to be available after initial setup
  hosts: new_servers
  ignore_unreachable: yes
  tasks:
    - name: Wait for SSH to be available
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        state: started
        delay: 10

- name: Configure servers
  hosts: all:!new_servers
  become: yes
  roles:
    - initial_setup

- name: Install docker
  hosts: all:!new_servers
  become: yes
  roles:
    - install_docker

- name: Install gitlab
  hosts: all:!new_servers
  become: yes
  roles:
    - install_gitlab