---
- name: Check if all servers are unreachable
  hosts: new_servers
  ignore_unreachable: yes
  tasks:
    - name: Create a list of reachable hosts
      set_fact:
        reachable_hosts: "{{ reachable_hosts | default([]) + [inventory_hostname] }}"
      when: ansible_facts | length != 0

    - name: Gather all reachable_hosts from all hosts
      set_fact:
        all_reachable_hosts: "{{ groups['all'] | map('extract', hostvars, 'reachable_hosts') | map('default', []) | list | flatten }}"

    - name: Add a host to group
      add_host:
        name: "{{ item }}"
        groups: reachable_hosts
      loop: "{{ all_reachable_hosts }}"

- name: Configure new servers
  hosts: reachable_hosts
  ignore_unreachable: yes
  gather_facts: yes
  become: yes
  roles:
    - initial_setup

- name: Wait for SSH to be available after initial setup
  hosts: new_servers
  ignore_unreachable: yes
  tasks:
    - name: Wait for SSH to be available
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        state: started
        delay: 10

- name: Configure servers
  hosts: all:!new_servers
  become: yes
  roles:
    - initial_setup

- name: Install docker
  hosts: all:!new_servers
  become: yes
  roles:
    - install_docker

- name: Install kafka
  hosts: kafka-servers
  become: yes
  roles:
    - install_kafka

- name: Install nginx
  hosts: web-servers
  become: yes
  roles:
    - install_nginx

- name: Install gitlab
  hosts: gitlab-servers
  become: yes
  roles:
    - install_gitlab

- name: Install monitoring
  hosts: all:!new_servers
  become: yes
  roles:
    - install_monitoring