---
# =================================================
# 🔗 1️⃣ Добавление официального репозитория Docker
# =================================================

- name: Include Docker repository setup tasks
  include_tasks: docker_repo.yml

# ======================================
# 🐳 2️⃣ Установка Docker
# ======================================

# 🚀 Устанавливаем Docker (RedHat)
- name: Install Docker for RedHat family
  yum:
    name: docker-ce
    state: present
  when: ansible_os_family == "RedHat"

# 🚀 Устанавливаем Docker (Debian)
- name: Install Docker for Debian family
  apt:
    name: docker-ce
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

# ======================================
# ⚙️ 3️⃣ Запуск и включение Docker
# ======================================

# 🔄 Включаем автозапуск Docker и запускаем его
- name: Enable and start Docker service
  systemd:
    name: docker
    state: started
    enabled: yes

# ======================================
# 🔧 4️⃣ Инициализация Swarm 
# ======================================

# 🛠️ Инициализация Docker Swarm на менеджере
- name: Initialize Docker Swarm on manager node
  include_tasks: init_docker_swarm.yml
  when: hostvars[inventory_hostname].get('master', false)

# 🖧 Подключаем воркер ноды к Docker Swarm
- name: Join workers to Swarm
  shell: docker swarm join --token {{ swarm_worker_token }} {{ swarm_manager_host }}:2377
  when: not hostvars[inventory_hostname].get('master', false)
  ignore_errors: yes

# ===============================================
# 👤 5️⃣ Добавление пользователей в группу Docker
# ===============================================

# 👥 Добавляем пользователей в группу Docker, чтобы запускать контейнеры без sudo
- name: Add users to docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  with_items: "{{ docker_settings.users }}"

# ======================================
# 🛠️ 6️⃣ Установка Docker Compose
# ======================================

- name: Install docker-compose
  include_tasks: install_docker_compose.yml
  when: install_docker_compose