---

# ====================================================
# 🔄 Перезагрузка nginx для применения новой конфигурации
# ====================================================
- name: Reload nginx
  systemd:
    name: nginx
    state: reloaded