---
# vars file for install_kafka

kafka_version: "3.9.0"
kafka_download_url: "https://downloads.apache.org/kafka/{{ kafka_version }}/kafka_2.13-{{ kafka_version }}.tgz"
java_package_debian: "openjdk-11-jdk"
java_package_rethat: "java-11-openjdk-devel"
kafka_group: "kafka"
kafka_user: "kafka"
kafka_install_dir: "/opt/kafka"
kafka_data_dir: "/var/lib/kafka"
kafka_logs_dir: "/var/log/kafka"
kafka_config_dir: "{{ kafka_install_dir }}/config"

listeners_port: 9092
controller_port: 9093