---
# ======================================
# 🖥️ 1️⃣ Изменение hostname на локальном хосте
# ======================================
- name: Change hostname
  ansible.builtin.hostname:
    name: "{{ hostvars[inventory_hostname]['hostname'] }}"

# ======================================
# 🔍 2️⃣ Сбор информации о новых серверах
# ======================================
- name: Collect remote host details
  ansible.builtin.setup:
  delegate_to: "{{ item }}"
  delegate_facts: true
  loop: "{{ groups['reachable_hosts'] }}"

# ======================================
# 📝 3️⃣ Обновление /etc/hosts на локальном хосте
# ======================================
- name: Ensure correct IP and hostname in /etc/hosts to local host
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "^.*\\s+{{ hostvars[item]['hostname'] }}$"
    line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ hostvars[item]['hostname'] }}"
    state: present
    backup: yes
  delegate_to: localhost
  loop: "{{ groups['reachable_hosts'] }}"
