---
# ======================================
# 🖥️ 1️⃣ Изменение hostname на локальном хосте
# ======================================
- name: Change hostname
  ansible.builtin.hostname:
    name: "{{ hostvars[inventory_hostname]['hostname'] }}"

# ======================================
# 🔍 2️⃣ Сбор информации о новых серверах
# ======================================
- name: Collect remote host details
  ansible.builtin.setup:
  delegate_to: "{{ item }}"  # Выполняем команду на удалённых хостах
  delegate_facts: true  # Сохраняем собранные данные в hostvars
  loop: "{{ groups['new_servers'] }}"  # Обрабатываем только хосты из группы "new_servers"

# ======================================
# 📝 3️⃣ Обновление /etc/hosts на локальном хосте
# ======================================
- name: Ensure correct IP and hostname in /etc/hosts to local host
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "^.*\\s+{{ hostvars[item]['hostname'] }}$"  # Поиск строки с hostname
    line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ hostvars[item]['hostname'] }}"  # Записываем IP и hostname
    state: present
    backup: yes  # Создаём резервную копию /etc/hosts перед изменением
  delegate_to: localhost  # Выполняем на локальном хосте
  loop: "{{ groups['new_servers'] }}"  # Перебираем новые сервера
