---
# ======================================
# 📂 1️⃣ Подключение переменных
# ======================================
- name: Include User variables
  include_vars: vars/users.yml

- name: Include SSH variables
  include_vars: vars/ssh.yml

# ======================================
# 🔧 2️⃣ Настройка конфигурации SSH
# ======================================
- name: Ensure sshd_config.d directory exists
  file:
    path: /etc/ssh/sshd_config.d
    state: directory
    mode: '0644'

- name: Remove all files from sshd_config.d
  shell: rm -rf /etc/ssh/sshd_config.d/*

- name: Deploy SSH configuration from template
  template:
    src: ssh_config.j2
    dest: /etc/ssh/sshd_config.d/coustom_ssh.conf
    mode: '0644'
  notify: Restart SSH Service

# ===============================================
# 🔑 3️⃣ Генерация SSH-ключей на локальной машине
# ===============================================
- name: Ensure /tmp/ssh directory exists
  file:
    path: /tmp/ssh
    state: directory
    mode: '0755'
  delegate_to: localhost
  become: no

- name: Generate SSH key pair on local machine
  openssh_keypair:
    path: "/tmp/ssh/id_ansible"
    type: rsa
    size: 4096
    force: no
  delegate_to: localhost
  run_once: true
  become: no

- name: Copy SSH private key to localhost
  copy:
    src: "/tmp/ssh/id_ansible"
    dest: "~/.ssh/id_rsa"
    mode: "0600"
  delegate_to: localhost
  become: no

- name: Copy SSH public key to localhost
  copy:
    src: "/tmp/ssh/id_ansible.pub"
    dest: "~/.ssh/id_rsa.pub"
    mode: "0600"
  delegate_to: localhost
  become: no

# ===========================================================
# 🔍 4️⃣ Чтение и копирование SSH-ключей на удалённые сервера
# ===========================================================

# 🔹 Читаем публичный ключ
- name: Read public SSH key
  set_fact:
    ssh_public_key: "{{ lookup('file', '/tmp/ssh/id_ansible.pub') }}"
  delegate_to: localhost
  run_once: true
  become: no

# 🔹 Читаем приватный ключ
- name: Read private SSH key
  set_fact:
    ssh_private_key: "{{ lookup('file', '/tmp/ssh/id_ansible') | regex_replace('$', '\n') }}"
  delegate_to: localhost
  run_once: true
  become: no

# 🔹 Копируем публичный ключ на удалённые серверы (добавляем в authorized_keys)
- name: Copy SSH public key to remote servers
  authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ ssh_public_key }}"
  with_items: "{{ users }}"
  when: item.create_ssh_key | default(true)

# 🔹 Копируем приватный ключ на удалённые серверы (в ~/.ssh/id_rsa)
- name: Copy SSH private key file to remote servers
  copy:
    content: "{{ ssh_private_key }}"
    dest: "/home/{{ item.name }}/.ssh/id_rsa"
    mode: "0600"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  with_items: "{{ users }}"
  when: item.create_ssh_key | default(true)
