---
# ======================================
# 🔍 1️⃣ Сбор информации с удалённых хостов (кроме new_servers)
# ======================================
- name: Collect remote host details
  ansible.builtin.setup:
  delegate_to: "{{ item }}"  # Выполняем команду на удалённых хостах
  delegate_facts: true  # Сохраняем собранные данные в hostvars
  loop: "{{ groups['all'] | difference(groups['new_servers']) }}"  # Исключаем new_servers
  run_once: true  # Выполняем только один раз (делегирование затрагивает все хосты)

# ======================================
# 📝 2️⃣ Обновление /etc/hosts (кроме new_servers)
# ======================================
- name: Ensure correct IP and hostname in /etc/hosts for all hosts except new_servers
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "^.*\\s+{{ hostvars[item]['ansible_hostname'] }}$"  # Проверяем, есть ли запись с таким hostname
    line: "{{ hostvars[item]['ansible_default_ipv4']['address'] | default('127.0.0.1') }} {{ hostvars[item]['ansible_hostname'] }}"  # Записываем IP и hostname
    state: present
    backup: yes  # Создаём резервную копию /etc/hosts перед изменением
  loop: "{{ groups['all'] | difference(groups['new_servers']) }}"  # Исключаем new_servers
  when: hostvars[item]['ansible_default_ipv4'] is defined  # Выполняем только если есть IP
