---
# ======================================
# 📂 1️⃣ Подключение переменных пользователей
# ======================================
- name: Include User variables
  include_vars: vars/users.yml

# ======================================
# 👥 2️⃣ Создание пользователей
# ======================================
- name: Create users
  user:
    name: "{{ item.name }}"
    password: "{{ item.password | password_hash('sha512') }}"  # Хешируем пароль перед записью
    state: present
    shell: /bin/bash
  with_items: "{{ users }}"
  when: users is defined  # Выполняем, только если переменная users определена

# ======================================
# 🔑 3️⃣ Добавление пользователей в группы
# ======================================

# 🔹 Добавляем пользователей в sudo группу, если root == true
- name: Add user to sudo group if root is true
  user:
    name: "{{ item.name }}"
    groups: "{{ 'sudo' if ansible_os_family == 'Debian' else 'wheel' }}, admin"
    append: yes
  with_items: "{{ users }}"
  when: item.root == true  # Проверяем, нужно ли дать sudo-доступ

# ======================================
# ⚙️ 4️⃣ Настройка sudoers
# ======================================
- name: Configure sudoers file
  template:
    src: sudoers.j2
    dest: /etc/sudoers.d/users
    mode: '0440'  # Безопасные права доступа
