---
# ============================================================
# 🚨  Остановка выполнения Playbook при `skip_playbook: true`
# ============================================================
- name: Show skip message
  debug:
    msg: "🚨 Playbook execution is disabled by `skip_playbook`. Exiting..."
  run_once: true
  when: skip_playbook | default(false)

- name: Stop execution if `skip_playbook` is enabled
  meta: end_play
  when: skip_playbook | default(false)

# =====================================
# 1️⃣ Проверки системы перед настройкой
# =====================================
- name: Run system checks
  include_tasks: check_system.yml

# ==========================================
# 2️⃣ Открытие необходимых портов (Firewall)
# ==========================================
- name: Ensure required ports are open
  include_tasks: configure_firewall.yml
  when: allow_ports | default([]) | length > 0  # Выполняем только если указаны порты

# ==============================
# 3️⃣ Настройка hostname
# ==============================
- name: Change hostnames to local host
  include_tasks: configure_hostnames_local.yml
  when: "'new_servers' in group_names and change_hostnames"

- name: Change hostnames to remote hosts
  include_tasks: configure_hostnames_remote.yml
  when: "'new_servers' not in group_names and change_hostnames"

# ==============================
# 4️⃣ Создание пользователей
# ==============================
- name: Include tasks for users creation
  include_tasks: create_users.yml
  when: user_created

# ==============================
# 5️⃣ Настройка SSH
# ==============================
- name: Configure ssh
  include_tasks: configure_ssh.yml
  when: edit_ssh_settings

# ==============================
# 6️⃣ Обновление системы
# ==============================
- name: Update system
  include_tasks: update_system.yml
  when: upgrade_system
