---
- name: Update package lists
  apt:
    update_cache: yes
  become: yes

- name: Upgrade all packages
  apt:
    upgrade: dist
  become: yes

- name: Remove unnecessary packages
  apt:
    autoremove: yes
  become: yes