---
# ======================================
# 🔄 1️⃣ Обновление пакетов и очистка кеша
# ======================================

# 🔹 Обновление всех пакетов до последней версии
- name: Update all packages 
  yum:
    name: "*" 
    state: latest
  become: yes  

# 🔹 Очистка кэша пакетов yum
- name: Clean up package cache 
  command: yum clean all  
  become: yes  