---
# ===============================================
# 🛠️ Настройка конфигурации Kafka и создание сервисов
# ===============================================

- name: Set up Kafka configuration file
  template:
    src: kafka-server.properties.j2
    dest: "{{ kafka_config_dir }}/kraft/server.properties"
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    mode: "0644"

- name: Create Kafka systemd service
  template:
    src: kafka.service.j2
    dest: "/etc/systemd/system/kafka.service"
    owner: root
    group: root
    mode: "0644"

# ====================================================
# 🔑 Генерация случайного UUID для кластера Kafka
# ====================================================

- name: Run generate random UUID
  command: /opt/kafka/bin/kafka-storage.sh random-uuid
  register: kafka_uuid_output
  run_once: true

# ==========================================================
# 📂 Инициализация логов для KRaft (Kafka Raft) с UUID
# ==========================================================
- name: Init kraft logs dir
  become_user: "{{ kafka_user }}"
  shell: "{{ kafka_install_dir }}/bin/kafka-storage.sh format --config {{ kafka_config_dir }}/kraft/server.properties --cluster-id {{ kafka_uuid_output.stdout }}"
