---
# ========================================================
# 🔄 Перезагрузка systemd для распознавания сервиса Kafka
# ========================================================

- name: Reload systemd to recognize Kafka service
  systemd:
    daemon_reload: yes

# ===================================
# ⚙️ Включение и запуск службы Kafka 
# ===================================

- name: Enable Kafka service
  systemd:
    name: kafka
    enabled: yes
    state: started