---
# ============================================================
# 🚨 Остановка выполнения Playbook при `skip_playbook: true`
# ============================================================
- name: Show skip message
  debug:
    msg: "🚨 Playbook execution is disabled by `skip_playbook`. Exiting..."
  run_once: true
  when: skip_playbook | default(false)
  
- name: Stop execution if `skip_playbook` is enabled
  meta: end_play
  when: skip_playbook | default(false)

# ============================================================
# 🚨 Удаление кластера, если переменная `delete_cluster` установлена в true
# ============================================================
- name: Delete cluster
  include_tasks: delete_cluster.yml
  when: delete_cluster

# ============================================================
# 🖥️ Настройка серверов
# ============================================================
- name: Configure servers
  include_tasks: configure_servers.yml

# ============================================================
# 📦 Установка Kafka
# ============================================================
- name: Install kafka
  include_tasks: install_kafka.yml

# ============================================================
# ⚙️ Настройка Kafka
# ============================================================
- name: Configure kafka
  include_tasks: configure_kafka.yml

# ============================================================
# 🚀 Запуск сервиса Kafka
# ============================================================
- name: launching the kafka service
  include_tasks: launching_kafka_service.yml
